### PR TITLE
updated project path within vagrant guest and bound rails to 0.0.0.0 …

### PR DESCRIPTION
**Pull request by lklepner**
…when starting up.

### CODE REVIEW

**Comment by mgiraldo** [comment]
the current instructions worked for me so i think these make them unnecessarily specific

**Comment by lklepner** [comment]
I wasn't able to access the rails server from the vagrant guest without binding to 0.0.0.0. The default 127.0.0.1 doesn't seem to respond to vagrant forwarded requests.

**Comment by mgiraldo** [comment]
ok so maybe change the pull request so that it has both options? eg: "if this doesnt work try this other setting"

what OS are you in? using mac os el capitan here

**Comment by lklepner** [comment]
mac yosemite here. i'll revise the PR

**Pull request closed without merging**
