### PR TITLE
Added Hotkeys + Spacenavigator to Layers page, improved overall performance

### PR DESCRIPTION
**Pull request by lklepner**
- moved map controls in global JS file, reducing code duplication
- added hotkey and spacenavigator support to Layers page 
- corrected bug when zooming a single From or To map on the Rectify page
- corrected bug where map page without url hash failed to fully load hotkeys/spacenavigator for Show tab
- improved spacenavigator warp map selection (pressing the left or right buttons enables the From or To map, pressing both buttons are once enables both)

### CODE REVIEW

**Comment by lklepner** [comment]
Layers example (note that only one map in the layer is rectified)
http://mapwarper.livefeed.net/warper/layers/7

Map example 
http://mapwarper.livefeed.net/warper/maps/1

**Comment by mgiraldo** [comment]
we should disable scroll-to-zoom in the layer list page because there it _is_ very annoying… you are very likely to be scrolling past the map most of the time… in the other ones it's ok because there's usually nothing below the map or it is an admin view (eg: rectify)

(for some reason the main Minus key still zooms in for me in Firefox… can you reproduce?)

**Comment by lklepner** [comment]
I see what you're saying about scrolling past the map to get to the list.. 

As an immediate fix - I pushed a commit that disables the mousewheel. 

In the longer term - I wonder if the page layout could be revised so there isn't an inherent need to scroll past the map to get down to the list?

**Comment by mgiraldo** [comment]
i'm getting double zoom ins and single zoom outs: pressing Plus zooms in farther than what pressing Minus zooms out of (top row buttons, Firefox 46 Mac)

**Comment by lklepner** [comment]
just pushed a commit which disables the double zoom

**Pull request merged**
